gpg changes and scm details.
javaee/javax.xml.registry pull request #2
Opened 2018-03-14 07:02 UTC by sumauppa

gpg changes and scm details.

2018-03-15 09:06 UTC, yaminikb approved these changes

2018-03-16 05:14 UTC, yaminikb requested changes

2018-03-16 05:14 UTC, yaminikb commented on pom.xml
>          <license>
Please fix license url

2018-03-16 05:28 UTC, sumauppa commented on pom.xml
>          <license>
Updated License URL.

2018-03-16 05:32 UTC, yaminikb approved these changes

2018-03-16 05:33 UTC, merged